# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Eyebolt
tagline:          'A Jekyll theme'
description:      'Custom Software Solutions'
url:              http://www.eyebolt.com
baseurl:          /
#baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:           'John Gardner'
  url:            http://johngardner.name

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Eyebolt/eyebolt.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
